### ISSUE TITLE
Cannot generate conda lock files

### ISSUE THREAD

**Issue by atharva-2001** [radioactivedecay/radioactivedecay#100]
#### What is the issue?

Hi from TARDIS! We use the radioactivedecay package in our environment and one of our pipelines failed recently at the generate lockfile step. Turns out we can't generate them even with just python and the package. Would you mind helping us with this?

#### Steps to reproduce

Here is the env file with which I tried to generate the conda lock file-
https://github.com/atharva-group/GA-test/blob/main/demo_env.yml

```yml
name: demo

channels:
  - conda-forge

dependencies:
  - python
  - radioactivedecay
```

And the commands which I ran-
```
conda-lock -f demo_env.yml -p linux-64 -p osx-64 # this fails
conda lock render conda-lock.yml
```
The linux file builds correctly- but the osx fails-

Here is the shortened error log-
```py
Traceback (most recent call last):
  File "/usr/share/miniconda3/lib/python3.10/site-packages/conda/_vendor/boltons/setutils.py", line 247, in remove
    didx = self.item_index_map.pop(item)
KeyError: PackageRecord(_hash=-787167132428323713, name='__osx', version='0', build='0', build_number=0, channel=Channel("@"), subdir='osx-64', fn='__osx', md5='12345678901234567890123456789012', package_type='virtual_system')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
    return func(*args, **kwargs)
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
    raise e
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
    exit_code = _wrapped_main(*args, **kwargs)
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
    result = do_call(parsed_args, p)
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
    exit_code = create(args, parser)
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
    return install(args, parser, "create")
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 590, in install
    conda_transaction = to_txn(
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/utils.py", line 447, in to_txn
    final_precs = compute_final_precs(
  File "/usr/share/miniconda3/lib/python3.10/site-packages/mamba/utils.py", line 373, in compute_final_precs
    final_precs.remove(i_rec)
  File "/usr/share/miniconda3/lib/python3.10/site-packages/conda/_vendor/boltons/setutils.py", line 249, in remove
    raise KeyError(item)
KeyError: PackageRecord(_hash=-787167132428323713, name='__osx', version='0', build='0', build_number=0, channel=Channel("@"), subdir='osx-64', fn='__osx', md5='12345678901234567890123456789012', package_type='virtual_system')
```
Here is the workflow yml that failed-
https://github.com/atharva-group/GA-test/blob/main/.github/workflows/lock.yml

The action that failed-
https://github.com/atharva-group/GA-test/actions/runs/6403267454/job/17381429562

#### Environment
OS version:  Ubuntu Latest
Python version:  3.10.12
radioactivedecay version: 0.4.21
Installed via: conda-forge

**Comment by alexmalins** [comment]
Hey @atharva-2001 
I'm not completely sure what is causing this, but I found two workarounds.

1. Use `--no-mamba` flag:
```
conda-lock -f demo_env.yml -p linux-64 -p osx-64 --no-mamba # this now works
conda lock render conda-lock.yml
```

2. Pin the Python version in the env yaml:
```
name: demo

channels:
  - conda-forge

dependencies:
  - python=3.10
  - radioactivedecay
  ```
  
Either of these methods will successfully generate the lock files.


Again I'm not sure what the problem is, but reading [here](https://github.com/sagemath/sage/pull/35986) suggests this is more a conda version / conda-lock issue than anything specific this package has caused. Hopefully one of the above workarounds is palatable for TARDIS - of the two, I guess the first is the least worst option.
